name: tugas_10
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get_cli: ^1.8.1
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.9.0
  firebase_storage: ^11.7.4
  image_picker: ^1.1.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  change_app_package_name: ^1.1.0
    
flutter_icons:
  image_path: "images/bunga_ungu.png"
  android: true
  ios: true
  # run command "flutter pub pub run flutter_launcher_icons:main" untuk mengupdate icon app
dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter


flutter_native_splash:
  color: "#FFFFFF"
  image: "images/bunga_ungu.png"
  # flutter pub run flutter_native_splash:create
flutter: 
  uses-material-design: true
  assets:
      - images/

  fonts: 
    - family: Poppins
      fonts: 
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-Black.ttf

